[package]
org = "wso2"
name = "create_read_associations"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.associations"
version = "3.0.0"
repository = "local"
