// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (443, config = {host: "api.hubapi.com"});

service / on ep0 {
    # Delete associations between two records
    #
    # + return - returns can be any of following types 
    # http:NoContent (No content)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function delete objects/[string objectType]/[string objectId]/associations/[string toObjectType]/[string toObjectId]() returns http:NoContent|AnydataDefault {
    }

    # Retrieve all associations by object type
    #
    # + after - The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results
    # + 'limit - The maximum number of results to display per page
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function get objects/[string objectType]/[string objectId]/associations/[string toObjectType](string? after, int:Signed32 'limit = 500) returns CollectionResponseMultiAssociatedObjectWithLabelForwardPaging|AnydataDefault {
    }

    # Remove associations
    #
    # + return - returns can be any of following types 
    # http:NoContent (No content)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function post associations/[string fromObjectType]/[string toObjectType]/batch/archive(@http:Payload BatchInputPublicAssociationMultiArchive payload) returns http:NoContent|AnydataDefault {
    }

    #  Create Default Associations
    #
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function post associations/[string fromObjectType]/[string toObjectType]/batch/associate/default(@http:Payload BatchInputPublicDefaultAssociationMultiPost payload) returns BatchResponsePublicDefaultAssociationOk|AnydataDefault {
    }

    # Associate records (labelled)
    #
    # + return - returns can be any of following types 
    # http:Created (successful operation)
    # http:MultiStatus (multiple statuses)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function post associations/[string fromObjectType]/[string toObjectType]/batch/create(@http:Payload BatchInputPublicAssociationMultiPost payload) returns BatchResponseLabelsBetweenObjectPair|BatchResponseLabelsBetweenObjectPairWithErrorsMultiStatus|AnydataDefault {
    }

    # Delete Specific Labels
    #
    # + return - returns can be any of following types 
    # http:NoContent (No content)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function post associations/[string fromObjectType]/[string toObjectType]/batch/labels/archive(@http:Payload BatchInputPublicAssociationMultiPost payload) returns http:NoContent|AnydataDefault {
    }

    # Retrieve associations
    #
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:MultiStatus (multiple statuses)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function post associations/[string fromObjectType]/[string toObjectType]/batch/read(@http:Payload BatchInputPublicFetchAssociationsBatchRequest payload) returns BatchResponsePublicAssociationMultiWithLabelOk|BatchResponsePublicAssociationMultiWithLabelWithErrorsMultiStatus|AnydataDefault {
    }

    # Report high usage
    #
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function post associations/usage/high\-usage\-report/[int:Signed32 userId]() returns ReportCreationResponseOk|AnydataDefault {
    }

    # Associate records (default)
    #
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function put objects/[string fromObjectType]/[string fromObjectId]/associations/default/[string toObjectType]/[string toObjectId]() returns BatchResponsePublicDefaultAssociation|AnydataDefault {
    }

    # Associate records (labelled)
    #
    # + return - returns can be any of following types 
    # http:Created (successful operation)
    # http:DefaultStatusCodeResponse (An error occurred.)
    resource function put objects/[string objectType]/[string objectId]/associations/[string toObjectType]/[string toObjectId](@http:Payload AssociationSpec[] payload) returns LabelsBetweenObjectPairCreated|AnydataDefault {
    }
}
